name: Clang Format Check

on:
  push:
    paths:
      - '**.cpp'
      - '**.h'
    branches: [ main ]
  pull_request:
    paths:
      - '**.cpp'
      - '**.h'
    branches: [ main ]

jobs:
  clang-format-check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Install clang-format
      run: sudo apt-get install -y clang-format
      
    - name: Create .clang-format file
      run: |
        cat > .clang-format << 'EOL'
        BasedOnStyle: Mozilla
        AlignAfterOpenBracket: Align
        AlignConsecutiveMacros: 'true'
        AlignConsecutiveAssignments: 'true'
        AlignConsecutiveDeclarations: 'true'
        AlignEscapedNewlines: Right
        AlignOperands: 'true'
        AlignTrailingComments: 'true'
        AllowAllArgumentsOnNextLine: 'false'
        AllowAllConstructorInitializersOnNextLine: 'false'
        AllowAllParametersOfDeclarationOnNextLine: 'false'
        AllowShortBlocksOnASingleLine: 'false'
        AllowShortCaseLabelsOnASingleLine: 'false'
        AllowShortFunctionsOnASingleLine: None
        AllowShortIfStatementsOnASingleLine: Never
        AllowShortLambdasOnASingleLine: None
        AllowShortLoopsOnASingleLine: 'false'
        AlwaysBreakAfterDefinitionReturnType: None
        AlwaysBreakAfterReturnType: None
        AlwaysBreakBeforeMultilineStrings: 'false'
        BinPackArguments: 'false'
        BinPackParameters: 'false'
        BreakBeforeBraces: Allman
        BreakConstructorInitializers: AfterColon
        BreakInheritanceList: AfterColon
        ConstructorInitializerAllOnOneLineOrOnePerLine: 'false'
        ConstructorInitializerIndentWidth: '4'
        Cpp11BracedListStyle: 'false'
        IncludeBlocks: Merge
        IndentCaseLabels: 'true'
        IndentPPDirectives: None
        IndentWidth: '4'
        KeepEmptyLinesAtTheStartOfBlocks: 'false'
        Language: Cpp
        MaxEmptyLinesToKeep: '1'
        PointerAlignment: Left
        SortIncludes: 'false'
        SortUsingDeclarations: 'false'
        SpaceAfterCStyleCast: 'false'
        SpaceAfterLogicalNot: 'false'
        SpaceAfterTemplateKeyword: 'false'
        SpaceBeforeAssignmentOperators: 'true'
        SpaceBeforeCpp11BracedList: 'false'
        SpaceBeforeCtorInitializerColon: 'true'
        SpaceBeforeInheritanceColon: 'true'
        SpaceBeforeParens: Never
        SpaceBeforeRangeBasedForLoopColon: 'false'
        SpaceInEmptyParentheses: 'false'
        SpacesInAngles: 'false'
        SpacesInCStyleCastParentheses: 'false'
        SpacesInContainerLiterals: 'true'
        SpacesInParentheses: 'false'
        SpacesInSquareBrackets: 'false'
        Standard: Cpp03
        TabWidth: '4'
        UseTab: Never
        ColumnLimit: 100
        EOL
    
    - name: Check code formatting
      run: |
        echo "Vérification du formatage du code TX..."
        find TX/src TX/lib -name "*.cpp" -o -name "*.h" | xargs clang-format -style=file --dry-run --Werror || exit 1
        echo "Vérification du formatage du code RX..."
        find RX/src RX/lib -name "*.cpp" -o -name "*.h" | xargs clang-format -style=file --dry-run --Werror || exit 1
        echo "✓ Formatage du code correct!"